name: Deploy Frontend Static

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy ke EC2 Frontend via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/UTS-Cloud
            git reset --hard
            git pull origin main
            sudo cp -r frontend/* /usr/share/nginx/html/
            sudo cp frontend/nginx.conf /etc/nginx/conf.d/default.conf
            sudo systemctl restart nginx
