name: Deploy Frontend Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy ke EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Masuk ke direktori UTS-Cloud/frontend
            cd /home/ec2-user/UTS-Cloud/frontend
            git pull origin main
            sudo docker build -t uts-frontend .
            sudo docker stop uts-frontend || true
            sudo docker rm uts-frontend || true
            sudo docker run -d -p 80:80 --name uts-frontend uts-frontend
